# Generated by Django 6.0.6 on 2026-06-23 08:21

import aquarium.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='活動名稱')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='網址代稱')),
                ('category', models.CharField(choices=[('show', '表演活動'), ('class', '體驗課程'), ('event', '特別活動'), ('conservation', '保育教育')], default='event', max_length=30, verbose_name='活動類型')),
                ('summary', models.CharField(max_length=180, verbose_name='活動摘要')),
                ('description', models.TextField(verbose_name='活動說明')),
                ('image_emoji', models.CharField(default='🐬', max_length=10, verbose_name='活動圖示')),
                ('starts_at', models.DateTimeField(verbose_name='開始時間')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('location', models.CharField(default='主展區', max_length=100, verbose_name='地點')),
                ('points_reward', models.PositiveIntegerField(default=0, verbose_name='報名獲得點數')),
                ('max_capacity', models.PositiveIntegerField(default=0, verbose_name='人數上限，0 表示不限')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '水族館活動',
                'verbose_name_plural': '水族館活動',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(default=aquarium.models.generate_ticket_no, max_length=30, unique=True, verbose_name='票券編號')),
                ('title', models.CharField(max_length=100, verbose_name='票券名稱')),
                ('ticket_type', models.CharField(choices=[('general', '一般入場券'), ('child', '兒童票'), ('event', '活動票'), ('gift', '贈品券')], default='general', max_length=30, verbose_name='票券類型')),
                ('status', models.CharField(choices=[('available', '可使用'), ('used', '已使用'), ('expired', '已過期')], default='available', max_length=20, verbose_name='狀態')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='有效期限')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_tickets', to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
            options={
                'verbose_name': '會員票券',
                'verbose_name_plural': '會員票券',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', '獲得點數'), ('spend', '使用點數'), ('adjust', '人工調整')], max_length=20, verbose_name='交易類型')),
                ('points', models.PositiveIntegerField(verbose_name='點數')),
                ('title', models.CharField(max_length=120, verbose_name='紀錄標題')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
            options={
                'verbose_name': '點數紀錄',
                'verbose_name_plural': '點數紀錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', '已報名'), ('cancelled', '已取消')], default='registered', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='報名時間')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='aquarium.activity', verbose_name='活動')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_registrations', to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
            options={
                'verbose_name': '活動報名',
                'verbose_name_plural': '活動報名',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
