# Generated by Django 6.0.6 on 2026-06-24 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPointGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_amount', models.PositiveIntegerField(verbose_name='消費金額')),
                ('earned_points', models.PositiveIntegerField(verbose_name='獲得點數')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_point_grants', to=settings.AUTH_USER_MODEL, verbose_name='會員')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_point_grants', to=settings.AUTH_USER_MODEL, verbose_name='操作店員')),
            ],
            options={
                'verbose_name': '店員加點紀錄',
                'verbose_name_plural': '店員加點紀錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
