# Generated by Django 6.0.6 on 2026-06-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0003_activityregistration_reward_granted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['starts_at'], 'verbose_name': '嘎比嘎比活動', 'verbose_name_plural': '嘎比嘎比活動'},
        ),
    ]
