"""Image helpers for official site content.

Product photos should stay clear and attractive on the storefront, while uploaded
files should be kept web-friendly and receive a subtle brand watermark.
"""
from __future__ import annotations

import logging
from io import BytesIO
from pathlib import Path, PurePosixPath

from django.conf import settings
from django.core.files.base import ContentFile
from PIL import Image, ImageEnhance, ImageOps, ImageStat

logger = logging.getLogger(__name__)

WATERMARK_ASSET = (
    Path(settings.BASE_DIR)
    / "pages"
    / "static"
    / "pages"
    / "images"
    / "guppyguppy-watermark-text.png"
)

JPEG_SUFFIXES = {".jpg", ".jpeg"}
WEBP_SUFFIXES = {".webp"}

# Web storefront optimization target.
# 1600px on the longest side is clear enough for product detail pages on mobile
# and desktop, while keeping media storage and page loading light.
MAX_PRODUCT_IMAGE_EDGE = 1600
MIN_WATERMARK_EDGE = 160
JPEG_QUALITY = 85
WEBP_QUALITY = 84
MAX_TARGET_BYTES = 950 * 1024


def _resize_to_width(image: Image.Image, target_width: int) -> Image.Image:
    """Resize proportionally by width."""
    target_width = max(80, int(target_width))
    if image.width == target_width:
        return image.copy()

    ratio = target_width / max(1, image.width)
    target_height = max(1, int(image.height * ratio))
    return image.resize((target_width, target_height), Image.Resampling.LANCZOS)


def _resize_longest_edge(image: Image.Image, max_edge: int = MAX_PRODUCT_IMAGE_EDGE) -> Image.Image:
    """Downscale large photos for web use without ever upscaling small images."""
    max_edge = max(400, int(max_edge))
    width, height = image.size
    longest = max(width, height)

    if longest <= max_edge:
        return image.copy()

    ratio = max_edge / longest
    target_size = (max(1, int(width * ratio)), max(1, int(height * ratio)))
    return image.resize(target_size, Image.Resampling.LANCZOS)


def _safe_float(value, default=None):
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _crop_square(image: Image.Image, crop_box=None) -> Image.Image:
    """Crop a product image to a square storefront master image.

    crop_box accepts normalized values generated by the admin crop UI:
    {"x": 0..1, "y": 0..1, "w": 0..1, "h": 0..1}. When no valid crop
    data is supplied, the image is center-cropped so all product images still
    share the same square composition and watermark placement.
    """
    width, height = image.size
    if width <= 0 or height <= 0:
        return image.copy()

    x = y = None
    side = min(width, height)

    if isinstance(crop_box, dict):
        nx = _safe_float(crop_box.get("x"))
        ny = _safe_float(crop_box.get("y"))
        nw = _safe_float(crop_box.get("w"))
        nh = _safe_float(crop_box.get("h"))

        if None not in (nx, ny, nw, nh) and nw > 0 and nh > 0:
            x = max(0, min(int(round(nx * width)), width - 1))
            y = max(0, min(int(round(ny * height)), height - 1))
            crop_width = max(1, int(round(nw * width)))
            crop_height = max(1, int(round(nh * height)))
            side = min(crop_width, crop_height, width - x, height - y)

    if not x and x != 0:
        side = min(width, height)
        x = (width - side) // 2
        y = (height - side) // 2

    side = max(1, min(int(side), width - x, height - y))
    return image.crop((x, y, x + side, y + side))


def _apply_alpha(image: Image.Image, opacity: float) -> Image.Image:
    """Apply opacity to an RGBA image without changing its colors."""
    watermark = image.convert("RGBA")
    opacity = max(0.0, min(float(opacity), 1.0))
    alpha = watermark.getchannel("A")
    alpha = ImageEnhance.Brightness(alpha).enhance(opacity)
    watermark.putalpha(alpha)
    return watermark


def _flatten_to_rgb(image: Image.Image) -> Image.Image:
    """Convert transparent images to RGB on white background for smaller JPEGs."""
    rgba = image.convert("RGBA")
    background = Image.new("RGB", rgba.size, "white")
    background.paste(rgba, mask=rgba.getchannel("A"))
    return background


def _mean_luminance(image: Image.Image) -> float:
    """Return average luminance (0..255) for adaptive watermark styling."""
    rgb = image.convert("RGB")
    r, g, b = ImageStat.Stat(rgb).mean[:3]
    return (0.2126 * r) + (0.7152 * g) + (0.0722 * b)


def _sample_region(image: Image.Image, box) -> Image.Image:
    left, top, right, bottom = box
    left = max(0, min(int(left), image.width - 1))
    top = max(0, min(int(top), image.height - 1))
    right = max(left + 1, min(int(right), image.width))
    bottom = max(top + 1, min(int(bottom), image.height))
    return image.crop((left, top, right, bottom))


def _tint_from_alpha(image: Image.Image, color: tuple[int, int, int]) -> Image.Image:
    """Colorize a watermark using only its alpha channel."""
    rgba = image.convert("RGBA")
    alpha = rgba.getchannel("A")
    colored = Image.new("RGBA", rgba.size, (*color, 0))
    colored.putalpha(alpha)
    return colored


def _build_outlined_mark(
    source: Image.Image,
    *,
    width: int,
    fill_color: tuple[int, int, int],
    fill_opacity: float,
    outline_color: tuple[int, int, int],
    outline_opacity: float,
    rotate: float = 0,
) -> Image.Image:
    """Prepare a watermark with a subtle opposite-tone outline for visibility."""
    base = _resize_to_width(source, width)
    fill = _apply_alpha(_tint_from_alpha(base, fill_color), fill_opacity)
    outline = _apply_alpha(_tint_from_alpha(base, outline_color), outline_opacity)

    canvas = Image.new("RGBA", (fill.width + 8, fill.height + 8), (255, 255, 255, 0))
    offsets = [(-2, 0), (2, 0), (0, -2), (0, 2), (-1, -1), (1, 1), (-1, 1), (1, -1)]
    for dx, dy in offsets:
        canvas.alpha_composite(outline, dest=(dx + 4, dy + 4))
    canvas.alpha_composite(fill, dest=(4, 4))

    if rotate:
        canvas = canvas.rotate(rotate, expand=True, resample=Image.Resampling.BICUBIC)

    return canvas


def _choose_watermark_style(region: Image.Image) -> dict:
    """Choose a dark or light watermark style based on local brightness."""
    luminance = _mean_luminance(region)
    if luminance < 92:
        return {
            "fill_color": (247, 250, 255),
            "outline_color": (18, 42, 104),
            "fill_opacity": 0.31,
            "outline_opacity": 0.18,
        }
    if luminance > 160:
        return {
            "fill_color": (18, 42, 104),
            "outline_color": (245, 249, 255),
            "fill_opacity": 0.30,
            "outline_opacity": 0.12,
        }
    return {
        "fill_color": (18, 42, 104),
        "outline_color": (236, 244, 255),
        "fill_opacity": 0.28,
        "outline_opacity": 0.12,
    }


def _choose_output_name(original_name: str, suffix: str) -> str:
    """Use JPEG for non-JPEG/WEBP photos to avoid very large PNG uploads."""
    original_path = PurePosixPath(original_name)
    suffix = suffix.lower()

    if suffix in JPEG_SUFFIXES or suffix in WEBP_SUFFIXES:
        return original_name

    return str(original_path.with_suffix(".jpg"))


def _save_jpeg(image: Image.Image, quality: int) -> bytes:
    buffer = BytesIO()
    _flatten_to_rgb(image).save(
        buffer,
        format="JPEG",
        quality=quality,
        optimize=True,
        progressive=True,
    )
    return buffer.getvalue()


def _save_webp(image: Image.Image, quality: int) -> bytes:
    buffer = BytesIO()
    image.convert("RGBA").save(buffer, format="WEBP", quality=quality, method=6)
    return buffer.getvalue()


def _save_image_to_bytes(image: Image.Image, output_name: str) -> bytes:
    """Save with storefront-friendly compression.

    JPEG/WEBP quality starts high enough for fish/product color detail. If the
    file is still too large, quality is reduced moderately but not to the point
    where product photos look obviously blurry.
    """
    suffix = Path(output_name).suffix.lower()

    if suffix in WEBP_SUFFIXES:
        for quality in (WEBP_QUALITY, 80, 76):
            output = _save_webp(image, quality)
            if len(output) <= MAX_TARGET_BYTES or quality == 76:
                return output

    for quality in (JPEG_QUALITY, 82, 78):
        output = _save_jpeg(image, quality)
        if len(output) <= MAX_TARGET_BYTES or quality == 78:
            return output

    return _save_jpeg(image, JPEG_QUALITY)


def apply_brand_watermark_to_image_field(image_field, crop_box=None) -> bool:
    """Optimize and watermark a Django ImageField product photo.

    The function returns True only when image_field.name changed and the caller
    should persist the updated name. Existing JPEG/WEBP paths are overwritten in
    place. PNG and other uploads are converted to a web-friendly JPEG file name.

    Returns:
        True when image_field.name changed and the model should be saved again.
        False when the image was overwritten in place or skipped safely.
    """
    if not image_field or not getattr(image_field, "name", ""):
        return False

    if not WATERMARK_ASSET.exists():
        logger.warning("Product watermark asset not found: %s", WATERMARK_ASSET)
        return False

    original_name = image_field.name

    try:
        with image_field.storage.open(original_name, "rb") as source_file:
            original = Image.open(source_file)
            original = ImageOps.exif_transpose(original)
            base = original.convert("RGBA")
    except Exception:
        logger.exception("Unable to open product image for watermark: %s", original_name)
        return False

    # Crop first so every storefront product image becomes a consistent square.
    # This keeps front-end cards aligned and makes the watermark position reliable.
    base = _crop_square(base, crop_box=crop_box)

    # Then compress by resizing the square storefront copy. This reduces memory,
    # media storage, and page load time before watermark composition.
    base = _resize_longest_edge(base)
    width, height = base.size

    if width < MIN_WATERMARK_EDGE or height < MIN_WATERMARK_EDGE:
        # Very small images are usually icons/thumbnails. Still optimize them,
        # but skip watermark to keep them readable.
        output_name = _choose_output_name(original_name, Path(original_name).suffix)
        output_bytes = _save_image_to_bytes(base, output_name)
        if output_name == original_name:
            try:
                with image_field.storage.open(original_name, "wb") as target_file:
                    target_file.write(output_bytes)
                return False
            except Exception:
                logger.info("Storage does not support in-place overwrite; saving optimized copy instead.")
        image_field.save(output_name, ContentFile(output_bytes), save=False)
        return image_field.name != original_name

    try:
        watermark_source = Image.open(WATERMARK_ASSET).convert("RGBA")
    except Exception:
        logger.exception("Unable to open watermark asset: %s", WATERMARK_ASSET)
        return False

    overlay = Image.new("RGBA", base.size, (255, 255, 255, 0))
    min_edge = min(width, height)

    # Sample local brightness so the watermark can switch between navy and
    # bright watermark variants. This keeps it visible on both white-tail fish
    # and dark-blue fish on black backgrounds.
    center_region = _sample_region(
        base,
        (
            width * 0.20,
            height * 0.22,
            width * 0.80,
            height * 0.78,
        ),
    )
    corner_region = _sample_region(
        base,
        (
            width * 0.66,
            height * 0.66,
            width,
            height,
        ),
    )

    # 1) Center diagonal text: stronger and adaptive so it remains readable on
    #    darker fish photos, while still staying soft enough for product pages.
    if min_edge >= 420:
        center_style = _choose_watermark_style(center_region)
        center_width = min(int(width * 0.64), int(height * 1.1), 920)
        center_mark = _build_outlined_mark(
            watermark_source,
            width=center_width,
            rotate=-18,
            **center_style,
        )
        center_position = ((width - center_mark.width) // 2, (height - center_mark.height) // 2)
        overlay.alpha_composite(center_mark, dest=center_position)

    # 2) Bottom-right signature: slightly crisper than before because this is a
    #    cleaner area and a good place for brand ownership without blocking fish details.
    corner_style = _choose_watermark_style(corner_region)
    corner_width = min(max(int(width * 0.26), 150), 360)
    corner_mark = _build_outlined_mark(
        watermark_source,
        width=corner_width,
        rotate=0,
        fill_opacity=min(0.34, corner_style["fill_opacity"] + 0.02),
        outline_opacity=min(0.2, corner_style["outline_opacity"] + 0.02),
        fill_color=corner_style["fill_color"],
        outline_color=corner_style["outline_color"],
    )
    margin = max(16, int(min_edge * 0.035))
    corner_position = (
        max(margin, width - corner_mark.width - margin),
        max(margin, height - corner_mark.height - margin),
    )
    overlay.alpha_composite(corner_mark, dest=corner_position)

    watermarked = Image.alpha_composite(base, overlay)
    output_name = _choose_output_name(original_name, Path(original_name).suffix)
    output_bytes = _save_image_to_bytes(watermarked, output_name)

    # Keep same path for JPEG/WEBP so existing product URLs remain stable.
    if output_name == original_name:
        try:
            with image_field.storage.open(original_name, "wb") as target_file:
                target_file.write(output_bytes)
            return False
        except Exception:
            logger.info("Storage does not support in-place overwrite; saving processed copy instead.")

    # For PNG/BMP/GIF/etc. create a JPEG storefront image to avoid oversized
    # media files. Delete the original only after the processed file is saved.
    old_name = image_field.name
    image_field.save(output_name, ContentFile(output_bytes), save=False)

    if image_field.name != old_name:
        try:
            if image_field.storage.exists(old_name):
                image_field.storage.delete(old_name)
        except Exception:
            logger.warning("Unable to delete original unoptimized product image: %s", old_name)

    return image_field.name != original_name
