# Generated by Django 6.0.6 on 2026-06-23 07:05

import django.db.models.deletion
import members.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.CharField(default=members.models.generate_member_no, max_length=20, unique=True, verbose_name='會員編號')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='手機')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='會員點數')),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold')], default='basic', max_length=20, verbose_name='會員等級')),
                ('line_user_id', models.CharField(blank=True, max_length=100, verbose_name='LINE User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
