# Generated by Django 6.0.6 on 2026-06-24 03:43

import django.db.models.deletion
import lottery.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_code', models.CharField(max_length=50, unique=True, verbose_name='獎項代碼')),
                ('prize_name', models.CharField(max_length=100, verbose_name='獎項名稱')),
                ('prize_desc', models.TextField(blank=True, verbose_name='獎項說明')),
                ('image_emoji', models.CharField(default='🎁', max_length=10, verbose_name='獎項圖示')),
                ('weight', models.PositiveIntegerField(default=1, help_text='數字越大越容易抽中。', verbose_name='抽中權重')),
                ('stock', models.IntegerField(blank=True, help_text='空白代表無限庫存；0 代表不可抽。', null=True, verbose_name='庫存')),
                ('points_cost', models.PositiveIntegerField(default=10, verbose_name='消耗點數')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('sort_order', models.PositiveIntegerField(default=999, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '常態抽獎獎項',
                'verbose_name_plural': '常態抽獎獎項',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LotterySpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_code', models.CharField(default=lottery.models.generate_spin_code, max_length=50, unique=True, verbose_name='抽獎編號')),
                ('spin_time', models.DateTimeField(auto_now_add=True, verbose_name='抽獎時間')),
                ('cost_points', models.PositiveIntegerField(default=10, verbose_name='消耗點數')),
                ('prize_name', models.CharField(max_length=100, verbose_name='獎項名稱快照')),
                ('stock_before', models.IntegerField(blank=True, null=True, verbose_name='抽獎前庫存')),
                ('stock_after', models.IntegerField(blank=True, null=True, verbose_name='抽獎後庫存')),
                ('balance_after', models.PositiveIntegerField(default=0, verbose_name='抽獎後點數')),
                ('result_status', models.CharField(choices=[('success', '成功'), ('failed', '失敗')], default='success', max_length=20, verbose_name='抽獎結果')),
                ('coupon_status', models.CharField(choices=[('unredeemed', '未兌換'), ('redeemed', '已兌換'), ('expired', '已過期'), ('void', '已作廢')], default='unredeemed', max_length=20, verbose_name='兌換狀態')),
                ('redeem_code', models.CharField(default=lottery.models.generate_redeem_code, max_length=50, unique=True, verbose_name='兌換碼')),
                ('redeem_qr_payload', models.TextField(blank=True, verbose_name='兌換 QR 內容')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='兌換時間')),
                ('redeemed_by', models.CharField(blank=True, max_length=100, verbose_name='核銷人員')),
                ('expire_at', models.DateTimeField(default=lottery.models.default_regular_coupon_expire_at, verbose_name='到期時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spins', to='lottery.lotteryprize', verbose_name='抽中獎項')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_spins', to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
            options={
                'verbose_name': '常態抽獎紀錄',
                'verbose_name_plural': '常態抽獎紀錄',
                'ordering': ['-spin_time'],
            },
        ),
    ]
